version: '3.7'

networks:
  observability:
    external: true

services:
  clean-node-types:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    entrypoint: sh ./.docker/entrypoint.sh
    # image: clean-node-types:1.2.3
    container_name: clean-node-types
    restart: always
    environment:
      MONGO_URL: mongodb://root:root@mongo:27017/clean-node-api?authSource=admin
      PORT: 5050
      ELASTIC_APM_SERVER_URL: http://apm:8200
    ports:
      - 5050:5050
      - 9222:9222
    volumes:
      - .:/usr/clean-node-types/app
    networks:
      - observability
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0.3
    restart: always
    ports:
      - 27017:27017
    container_name: clean-node-types-mongo
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - observability

