FROM node:16-alpine as install-dependencies

WORKDIR /usr/tdd-ddd-typescript-node/app

COPY package.json .

RUN yarn install --silent

FROM node:16-alpine as builder

WORKDIR /usr/tdd-ddd-typescript-node/app

COPY --from=install-dependencies /usr/tdd-ddd-typescript-node/app/node_modules ./node_modules

COPY . .

RUN yarn build

FROM node:16-alpine as production

WORKDIR /usr/tdd-ddd-typescript-node/app

LABEL org.opencontainers.image.authors="rafael.cavalcante@tallos.com.br"

USER node

COPY --from=builder /usr/tdd-ddd-typescript-node/app/dist ./dist
COPY --from=builder /usr/tdd-ddd-typescript-node/app/node_modules ./node_modules

CMD [ "node", "dist/main/server.js" ]

EXPOSE 5050